sudo: required
dist: trusty
cache: bundler
language: ruby
rvm:
- 2.4.4
- 2.3.8
addons:
  postgresql: '9.5'
before_install: gem install bundler -v 1.12.5
after_script: bundle exec codeclimate-test-reporter
